"Author:	Silen Mark
"Date:		2017年 7月29日 星期六 15时32分16秒 CST
" Vim options setting 



"if has('gui_running')
    ""set background=light
    "set background=dark
"else
    "set background=dark
"endif
"let g:rust_fold = 1
"set nofoldenable
set backspace=2
set cmdheight=2
set cursorline
set encoding=UTF-8
set foldlevelstart=1
set foldmethod=syntax
set hidden
set ignorecase smartcase
set incsearch
set matchtime=5
set mouse=a
set nobackup
set nohlsearch
set noswapfile
set nowritebackup
set number
set ruler
set scrolloff=999
set shiftwidth=4
set shortmess+=c
set showmatch gdefault
set signcolumn=yes
set softtabstop=4
set tabstop=4
set termguicolors
set updatetime=300
set wildmenu
"set wildmode=list,full
syntax on
"if exists('$TMUX')
	"set term=screen-256color
"endif
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o "防止粘贴文本自动加上注释
"set completeopt=longest,menuone
"----------键盘映射
let mapleader ="\<Space>"
tnoremap <Esc> <C-\><C-n>

"----------快速窗口切换{{{
nnoremap <C-k> <C-w>k
nnoremap <C-j> <C-w>j
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
"}}}

nnoremap <silent> [a     :previous<CR>
nnoremap <silent> ]a     :next<CR>
nnoremap <silent> [A     :first<CR>
nnoremap <silent> ]A     :last<CR>
nnoremap <silent> [b     :bprevious<CR>
nnoremap <silent> ]b     :bnext<CR>
nnoremap <silent> [B     :bfirst<CR>
nnoremap <silent> ]B     :blast<CR>
nnoremap <silent> [l     :lprevious<CR>
nnoremap <silent> ]l     :lnext<CR>
nnoremap <silent> [L     :lfirst<CR>
nnoremap <silent> ]L     :llast<CR>
nnoremap <silent> [<C-L> :lpfile<CR>
nnoremap <silent> ]<C-L> :lnfile<CR>
nnoremap <silent> [q     :cprevious<CR>
nnoremap <silent> ]q     :cnext<CR>
nnoremap <silent> [Q     :cfirst<CR>
nnoremap <silent> ]Q     :clast<CR>
nnoremap <silent> [<C-Q> :cpfile<CR>
nnoremap <silent> ]<C-Q> :cnfile<CR>
nnoremap <silent> [t     :tabprevious<CR>
nnoremap <silent> ]t     :tabNext<CR>
nnoremap <silent> [T     :tabfirst<CR>
nnoremap <silent> ]T     :tablast<CR>
nnoremap <silent> <leader>w :w<CR>
nnoremap <silent> <leader>q :q<CR>
nnoremap <silent> <leader>Q :q!<CR>
nnoremap <silent> <leader>ev :edit $MYVIMRC<CR>
nnoremap <silent> <leader>sv :source $MYVIMRC<CR>
nnoremap H ^
nnoremap L $
noremap <Down> gj
noremap <Up> gk
inoremap jk <Esc>
set pastetoggle=<F9>
set clipboard=unnamed

" auto format yaml
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
 
" buffer only
function! DeleteInactiveBufs()
    "From tabpagebuflist() help, get a list of all buffers in all tabs
    let tablist = []
    for i in range(tabpagenr('$'))
        call extend(tablist, tabpagebuflist(i + 1))
    endfor

    let nWipeouts = 0
    for i in range(1, bufnr('$'))
        if bufexists(i) && !getbufvar(i,"&mod") && index(tablist, i) == -1
            silent exec 'bwipeout' i

            let nWipeouts = nWipeouts + 1
        endif
    endfor
    echomsg nWipeouts . ' buffer(s) wiped out'
endfunction
command! Bonly :call DeleteInactiveBufs()

" Open in other edit tool
command! OpenInCode :call job_start(['code',expand('%:p')])
command! OpenInSubl :call job_start(['subl',expand('%:p')])

function! DeleteEmptyBuffers()
    let [i, n; empty] = [1, bufnr('$')]
    while i <= n
        if bufexists(i) && bufname(i) == ''
            call add(empty, i)
        endif
        let i += 1
    endwhile
    if len(empty) > 0
        exe 'bdelete' join(empty)
    endif
endfunction
command! BdeleteEmpty :call DeleteEmptyBuffers()

" Open HTML file via webbrower
if has('mac')
au FileType html command! OpenByDefault :call job_start(['open',expand('%:p')])
endif

"============================================================================}}}
